version: '3.8'

services:

  postgresergo:
      container_name: postgresergo
      image: postgres:15.2      
      volumes:
        - postgres_ergo_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: postgresergo
        POSTGRES_USER: postgresergo
        POSTGRES_PASSWORD: postgresErgo@123
      ports:
        - "5433:5432"

volumes:
  postgres_ergo_data: {}
